version: '3.7'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes: 
      - $PWD:/data/db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/sma-db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/sma-db-password
      # - POSTGRES_DB=sma
      # - POSTGRES_DB_FILE=sma
    networks:
      - spring_postgres_sma
    ports:
      - "5435:5432"
    secrets:
      - sma-db-user
      - sma-db-pass

  app:
    image: 'sma:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    secrets:
      - sma-admin-user
      - sma-admin-pass
    networks:
      - spring_postgres_sma
    ports:
      - "8080:8080"

secrets:
  sma-db-user:
    external: true
  sma-db-pass:
    external: true
  sma-admin-user:
    external: true
  sma-admin-pass:
    external: true

networks:
  spring_postgres_sma:
    external:
      true