spring:
  profiles.active: dev
---
jwt:
  secretkey: RandomSecret
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-108-128-104-50.eu-west-1.compute.amazonaws.com:5432/degqau050v0nbq
    username: ENC(e1dnM2MRtbVfwZZq3ZbLHTKzgtMZScpB)
    password: ENC(xfn81YkT6KEXvhNQOI+JpvlT2LtMopCQOoTBuPDlFm/OZ+oGZAE+uN13SIW0hYkAQycaRDGhNsoikTfpXCAp+FLNWFXVeFPqqTvOqOkizpk=)
  security:
    user:
      name: ENC(/55hbyre+yE5tb6zA6YyVBgzX/XuHIMn)
      password: ENC(VWX85f0hui4cpUTQp7/48A==)


server:
  port: 8080
# docker-secret:
#   bind-path: /run/secrets

#server.ssl.key-store-type=JKS
#server.ssl.key-store=classpath:keystore.jks
#server.ssl.key-store-password=123456
#server.ssl.key-alias=tomcat
#
#security.require-ssl=true

# jasypt.encryptor.algorithm=PBEWithMD5AndDES
# jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

#docker-secret.bind-path=/run/secrets

#debug=true
#trace=true

# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#spring.thymeleaf.cache=false
# Naming strategy
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
# Allows Hibernate to generate SQL optimized for a particular DBMS
