jwt:
    secretkey: secret
server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${docker-secret-sma-db-user}
        password: ${docker-secret-sma-db-pass}
        url: jdbc:postgresql://db:5432/${docker-secret-sma-db-user}
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    security:
        user:
            name: ${docker-secret-sma-admin-user}
            password: ${docker-secret-sma-admin-password}
docker-secret:
  bind-path: /run/secrets

#server.ssl.key-store-type=JKS
#server.ssl.key-store=classpath:keystore.jks
#server.ssl.key-store-password=123456
#server.ssl.key-alias=tomcat
#
#security.require-ssl=true


# jasypt.encryptor.algorithm=PBEWithMD5AndDES
# jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

#docker-secret.bind-path=/run/secrets

#debug=true
#trace=true

# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#spring.thymeleaf.cache=false
# Naming strategy
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
# Allows Hibernate to generate SQL optimized for a particular DBMS