spring:
  profiles.active: dev
---
jwt:
  secretkey: RandomSecret
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-203-255-149.compute-1.amazonaws.com:5432/d3jq82foah2oid
    username: ENC(Hpacqatq2x3Qhu7uNrhlHHjYRoTfnDCE)
    password: ENC(YJTQacsZWHU27+0oS+bjiHb4+peLmplvMY1aSiYYm6roveR+E/rTAnAj9jDPZHhqxnJaTCSJJOTtBmn/St9ftGYyrMicxjA+8yT8s/cr5+Q=)
  security:
    user:
      name: ENC(1hak+QtSRqr4mBHZJYSx2mUT8bchOLpf)
      password: ENC(G1d9E+0lFVNTXE6CYoATcA==)


server:
  port: 8080
# docker-secret:
#   bind-path: /run/secrets

#server.ssl.key-store-type=JKS
#server.ssl.key-store=classpath:keystore.jks
#server.ssl.key-store-password=123456
#server.ssl.key-alias=tomcat
#
#security.require-ssl=true

# jasypt.encryptor.algorithm=PBEWithMD5AndDES
# jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

#docker-secret.bind-path=/run/secrets

#debug=true
#trace=true

# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#spring.thymeleaf.cache=false
# Naming strategy
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
# Allows Hibernate to generate SQL optimized for a particular DBMS
